Repository nuke-ops/Nostra-13, pull requests merged in 2021-01, with the labels that each got.

#83 Cats should be able to SPEEN too.
  code/__DEFINES/tgs.dm
  code/modules/tgs/v5/api.dm
  icons/mob/mob.dmi
  icons/mob/pets.dmi
Labels: enhancement

#95 That's one small step for cit, one giant leap for engitopia.
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/construction.dm
  code/__HELPERS/string_lists.dm
  code/datums/components/material_container.dm
  code/datums/components/storage/storage.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/RPD.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/turf.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/mining/aux_base_camera.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/nodes/engineering_nodes.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
  icons/mob/radial.dmi
  icons/turf/debug.dmi
  tgstation.dme
Labels: Code Improvement, Feature, Port

#99 Fix for "That's one small step for cit, one giant leap for engitopia."
  code/game/turfs/simulated/floor.dm
Labels: Fix

#98 Revert "Revert "That's one small step for cit, one giant leap for engitopia.""
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/construction.dm
  code/__HELPERS/string_lists.dm
  code/datums/components/material_container.dm
  code/datums/components/storage/storage.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/RPD.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/turf.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/mining/aux_base_camera.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/nodes/engineering_nodes.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/stomach.dm
  icons/mob/radial.dmi
  icons/turf/debug.dmi
  tgstation.dme
Labels: FUCK, Tweak

#104 Upstream
  .github/workflows/ci_suite.yml
  .github/workflows/generate_documentation.yml
  _maps/map_files/SmolStation/SmolStation.dmm
  _maps/shuttles/axsbrig_smol.dmm
  _maps/shuttles/axsscioutpost_smol.dmm
  _maps/shuttles/mining_large.dmm
  code/game/objects/items/storage/bags.dm
  html/changelog.html
  html/changelogs/AutoChangeLog-pr-137.yml
  modular_sand/code/game/area/areas/shuttles.dm
  modular_sand/code/modules/tgs/custom_procs.dm
  modular_sand/icons/effects/mouse_pointers/pull.dmi
  modular_sand/icons/effects/mouse_pointers/throw.dmi
  tgstation.dme
Labels: Upstream

#105 Bluespace Locker
  _maps/_basemap.dm
  _maps/map_files/generic/CentCom_nostration.dmm
  code/__DEFINES/combat.dm
  code/_onclick/click.dm
  code/datums/status_effects/status_effect.dm
  code/modules/mob/mob_defines.dm
  modular_nostration/code/__HELPERS/unsorted.dm
  modular_nostration/code/controllers/subsystem/bluespace_locker.dm
  modular_nostration/code/game/area/Space_Station_13_areas.dm
  modular_nostration/code/game/objects/structures/crates_lockers/closets/bluespace_locker.dm
  modular_nostration/icons/obj/closet.dmi
  tgstation.dme
Labels: Feature, Map Edit

#106 Bluespace locker fixes
  _maps/map_files/generic/CentCom_nostration.dmm
  code/datums/components/stationloving.dm
  modular_nostration/code/controllers/subsystem/bluespace_locker.dm
Labels: Fix

#108 Increases the accuracy of the photocopier
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/abductor.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/paperwork/photocopier.dm
  modular_nostration/icons/ass/asscat.png
  modular_nostration/icons/ass/assgrey.png
  modular_nostration/icons/ass/asslizard.png
  modular_nostration/icons/ass/assmachine.png
  modular_nostration/icons/ass/assplasma.png
  modular_nostration/icons/ass/assslime.png
Labels: Feature, Port

#110 Upstream
  _maps/map_files/BoxStation/BoxStation.dmm
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/job.dm
  code/datums/elements/mob_holder.dm
  code/datums/explosion.dm
  code/game/atoms.dm
  code/game/machinery/colormate.dm
  code/game/objects/items/extinguisher.dm
  code/game/objects/items/pinpointer.dm
  code/game/world.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/neck/_neck.dm
  code/modules/clothing/under/accessories.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/point_bank.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  code/modules/mob/dead/new_player/sprite_accessories/socks.dm
  code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/death.dm
  code/modules/mob/living/death.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/kinkmate.dm
  config/sandstorm/config.txt
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/neck.dmi
  icons/mob/clothing/underwear.dmi
  icons/mob/hair.dmi
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/cloaks.dmi
  icons/obj/clothing/neck.dmi
  icons/obj/items_and_weapons.dmi
  modular_citadel/code/modules/client/loadout/_loadout.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/mask.dm
  modular_citadel/code/modules/client/loadout/neck.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
  modular_sand/code/controllers/configuration/entries/sandstorm.dm
  modular_sand/code/modules/client/loadout/boxers.dm
  modular_sand/code/modules/client/loadout/shirts.dm
  modular_sand/code/modules/client/loadout/socks.dm
  modular_sand/code/modules/clothing/underwear/shirts.dm
  modular_sand/code/modules/clothing/underwear/socks.dm
Labels: Upstream
