Repository nuke-ops/Nostra-13, pull requests merged in 2022-04, with the labels that each got.

#257 Revert pillow to 8.3.2
  modular_nostra/tools/mapmerge2/Prepare Maps.bat
  modular_nostra/tools/mapmerge2/README.md
  modular_nostra/tools/mapmerge2/convert.py
  modular_nostra/tools/mapmerge2/dmi.py
  modular_nostra/tools/mapmerge2/dmm.py
  modular_nostra/tools/mapmerge2/dmm2tgm.bat
  modular_nostra/tools/mapmerge2/frontend.py
  modular_nostra/tools/mapmerge2/map_scripts/apc_pixel_offsets.txt
  modular_nostra/tools/mapmerge2/map_scripts/clothingunderrepath.txt
  modular_nostra/tools/mapmerge2/map_scripts/cornersfix.txt
  modular_nostra/tools/mapmerge2/map_scripts/turfs2decals.txt
  modular_nostra/tools/mapmerge2/mapmerge.bat
  modular_nostra/tools/mapmerge2/mapmerge.py
  modular_nostra/tools/mapmerge2/merge_driver_dmi.py
  modular_nostra/tools/mapmerge2/precommit.py
  modular_nostra/tools/mapmerge2/requirements-install.bat
  modular_nostra/tools/mapmerge2/requirements.txt
  modular_nostra/tools/mapmerge2/tgm2dmm.bat
  modular_nostra/tools/mapmerge2/update_paths.py
  tools/requirements.txt
Labels: python, dependencies

#264 Some fixes
  code/modules/clothing/suits/utility.dm
  modular_nostra/code/game/objects/items/extinguisher.dm
  modular_nostra/code/modules/clothing/suits/miscellaneous.dm
  modular_nostra/icons/obj/items_and_weapons.dmi
Labels: Fix

#265 The Surplus Crate of Additions
  modular_nostra/code/datums/components/crafting/misc_crafting.dm
  modular_nostra/code/game/objects/items/murasama.dm
  modular_nostra/code/game/objects/items/polearms.dm
  modular_nostra/code/game/objects/items/weaponry.dm
  modular_nostra/code/modules/clothing/suits/armor.dm
  modular_nostra/code/modules/clothing/suits/mgr.dm
  modular_nostra/code/modules/mob/silicon/bladewolf.dm
  modular_nostra/code/modules/paperwork/origami.dm
  modular_nostra/code/modules/spells/spell_types/mime.dm
  modular_nostra/code/modules/uplink/uplink_bundles_plus.dm
  modular_nostra/code/modules/uplink/uplink_items/uplink_dangerous.dm
  modular_nostra/icons/mob/clothing/belt.dmi
  modular_nostra/icons/mob/clothing/head.dmi
  modular_nostra/icons/mob/clothing/head_muzzled.dmi
  modular_nostra/icons/mob/clothing/suit.dmi
  modular_nostra/icons/mob/clothing/suit_digi.dmi
  modular_nostra/icons/mob/inhands/two_handed_left.dmi
  modular_nostra/icons/mob/inhands/two_handed_right.dmi
  modular_nostra/icons/mob/inhands/weapons/polearm_lefthand.dmi
  modular_nostra/icons/mob/inhands/weapons/polearm_righthand.dmi
  modular_nostra/icons/mob/inhands/weapons/swords_lefthand.dmi
  modular_nostra/icons/mob/inhands/weapons/swords_righthand.dmi
  modular_nostra/icons/mob/widerobot.dmi
  modular_nostra/icons/obj/actions_minor_antag.dmi
  modular_nostra/icons/obj/clothing/belts.dmi
  modular_nostra/icons/obj/clothing/hats.dmi
  modular_nostra/icons/obj/clothing/suits.dmi
  modular_nostra/icons/obj/items_and_weapons.dmi
  modular_nostra/sound/weapons/shieldeploy.ogg
  modular_nostra/sound/weapons/shieldretract.ogg
  tgstation.dme
Labels: Feature

#270 Discstation
  _maps/discstation.dm
  _maps/discstation.json
  _maps/map_files/DiscStation/DiscStation.dmm
  _maps/shuttles/arrival_disc.dmm
  _maps/shuttles/emergency_disc.dmm
Labels: Map Edit

#271 Update maps.txt
  config/maps.txt
Labels: Config Update
